apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:bGGEyHqinYzNOIuxmjY/wrttP4SfDhvU,iv:1V34x4eDRFWQvhw/LFObAlOst+nNF6cjRYnJGQ0P85c=,tag:7W46mMxBJUMA+q7HvMWgfw==,type:str]
    client_secret: ENC[AES256_GCM,data:Sw7IE3BuQbgPVtucHTKjJsOx9PA0da8CGQyQvMyWmiHZ7n4/yI4hkuI9XX3D72+xZ5O0aE3EBCoKCb+lJKN8WhF2Q30kUBGLpKAFh0ubLo9mZ9V9,iv:r5ZMtR5tRmKP6XolLF0NklTlJUoINyb/EF7iXm7uUYs=,tag:xRqh8vq/Oq4P22urcgTU1w==,type:str]
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd1RrWlIza2F4VmNPMGtK
            WkprOEtFL3hQOHJxY2prNGQwQ29LUXREZFVVClVaMWxUeTJIY01ORy9hVVdRWnor
            RjUxK05aTnF1dEFNd0VvbW5ickJsck0KLS0tIE9QNm1qUGJCczZBUW83aEhGanZk
            U3RESVBkUVNSNEZCNVRQSzZ5NkxrMG8KnAi5otHM6sLxyopmp3JVV2Kbzr7CHGJz
            +tzbLEfnYkR2fUGVjbzhqGbORDmE92bQr+sT//gIMXgRbRmNwCQYWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m53mdahgvspp3j7smcw7y7zv9jw0kjqjaktyj4g88e5jlrj3cvzs7v64ms
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T16:41:33Z"
    mac: ENC[AES256_GCM,data:5o7O4wRDlLEdiy/S2vvnCnDErcQlziy9pucvOpwc26b5YBymlmtz6PmAA9ikv4sYHa8mzA2eS9wZjSIuNhcHmbEZ05S89rtSoqpouuY6+vdLxtubLxrSlrGufmqglqQHwQjHyRIXaEZR6O1UEYGvwnfY3UF1JunaHY3xTVKE64A=,iv:nQNgMpRGMOwyGeOA/ViO563DYZFAdfQCBJLwDoC0IQo=,tag:7oGvZTfuiHSCzEh/mgAs2A==,type:str]
    version: 3.13.3
