apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    theme: dark
    color: zinc
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |

    - Homelab:
        - Tailscale:
            href: https://console.tailscale.com
            description: tailnet
        - Grafana:
            href: https://grafana.toyger-court.ts.net
            description: Monitoring
        - Linkding:
            href: https://linkding.toger-court.ts.net
            description: Bookmarks

    - Kubernetes Docs:
        - Kubernetes Documentation:
            href: https://kubernetes.io/docs/home/
            description: Kubernetes
        - K3s Docs:
            href: https://docs.k3s.io/
            description: K3s
        - Flux Docs:
            href: https://fluxcd.io/flux/
            description: FluxCD

    - Git:
        - GitHub:
            href: https://github.com/brianemm99
            description: github
        - Codeberg:
            href: https://codeberg.org/
    - AI:
        - Claude:
            href: https://claude.ai/recents
        - PI:
            href: https://pi.dev/
            description: pi coding agent
        - Hermes:
            href: https://hermes-agent.nousresearch.com/docs
            description: hermes coding agent
        - Odysseus AI:
            href: https://odysseusai.dev/
            description: odysseus coding agent
        - Grok:
            href: https://grok.com/
        - Gippity:
            href: https://chatgpt.com/
            description: GPT

    - Tools:
        - Excalidraw:
            href: https://excalidraw.com/
            description: whiteboard
        - Fonts:
            - Nerd Font Icons:
                href: https://www.nerdfonts.com/cheat-sheet


  widgets.yaml: |

    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""
  proxmox.yaml: ""
