- OS Docs:
    - Arch:
        - abbr: Arch
          icon: arch-linux.png
          href: https://wiki.archlinux.org/title/Main_page
    - Hyprland:
        - abbr: Hypr
          icon: hyprland.png
          href: https://wiki.hypr.land/
    - Quickshell:
        - abbr: QS
          icon:  quickshhell.png
          href: https://quickshell.org/

- Dev Docs:
    - Helm:
        - icon: helm.png
          href: https://helm.sh/docs/
    - Terraform:
        - icon: terraform.png
					href: https://developer.hashicorp.com/terraform
    - Digital Ocean:
        - icon: digitalocean-light.png
          href: https://docs.digitalocean.com/products/
    - Podman:
        - icon: podman.png
          href: https://docs.podman.io/en/latest/
    - Docker:
        - icon: docker.png
          href: https://app.docker.com/
		- Cloudflare:
        - icon: cloudflare.png
          href: https://developers.cloudflare.com/tunnel/downloads/

- Media:
    - Youtube:
        - icon: youtube.png
          href: https://www.youtube.com/

- AI:
    - Claude:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/claude.png
          href: https://claude.ai/recents
    - PI:
        - icon: pi-coding-agent.png
          href: https://pi.dev/
          description: pi coding agent
    - Hermes:
        - icon: hermes-agent.png
          href: https://hermes-agent.nousresearch.com/docs
          description: hermes coding agent
    - Odysseus AI:
        - icon: odysseus.png
          href: https://odysseusai.dev/
          description: odysseus coding agent

- Learning:
    - KubeCraft:
        - icon: kubernetes-dashboard.png
          href: https://www.skool.com/kubecraft
    - Boot.Dev:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/brave-dev.png
          href: https://www.boot.dev/dashboard

- Coding:
    - Python:
        - icon: python.png
          href: https://www.python.org/doc/
    - Lua:
        - icon: lua.png
          href: https://www.lua.org/manual/5.5/

