theme: dark
color: zinc

background:
  image: /images/moon-ocean-orange.jpg

cardBlur: lg

layout:
  Homelab:
    style: row
    columns: 3
    header: false
  Kubernetes Docs:
    style: row
    columns: 3
    header: false
  Git:
    style: row
    columns: 2
    header: false
  Content:
    style: row
    columns: 3
    header: false
  AI:
    style: row
    columns: 4
    header: false
  Dev Docs:
    style: row
    columns: 3
    header: false
  OS Docs:
    style: row
    columns: 3
    header: false
  Coding:
    style: row
    columns: 2
    header: false
