- kubernetes:
    cluster:
      show: true
      cpu: true
      cputemp: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      disk: /host
      showLabel: true
      label: "NAS"
- search:
    provider: brave
    focus: true
    showSearchSuggestions: true
    target: _blank
- date-time:
    text_size: 2xl
    format:
      timeStyle: short
      hourCycle: h23
