- logo:
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/amd-light.png
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- datetime:
    text_size: 2xl
    format:
      timeStyle: short
      hourCycle: h23
- openmeteo:
    label: Baltimore
    latitude: 39.5246
    longitude: -76.6590
    timezone: America/New_York
    units: imperial
    cache: 5
- search:
    provider: brave
    focus: true
    showSearchSuggestions: false
    target: _blank

