apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:UdJApaQ9aRD5hUtL9BH8VRysR6o=,iv:UiJV4HSZmkvyAZMgf0PjieTveuXGknhZ1MbYcw+ciJw=,tag:ld2gU8adGSBNRDHI1ZA1Rg==,type:str]
    admin-user: ENC[AES256_GCM,data:il7TBGO30u0=,iv:sUPze4EzxOZNFUQkRKsFg5qJ6VtFiVwJ1bCFVJfH0E8=,tag:NdnCo360lbZrEIZFkvG3aA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbWJhWVgyejh4UkJUT1N2
            aWtMcGdWRW1xSEpSVm4yb3Y0YUhiTGdxZ2xFCm5KL1pvdVBmS05uSUFLam1TTG8z
            NDFHNWN0VUxFNXQ1TkZsNWFiSlN4cVEKLS0tIHlQNCt6clAvTng2Nk9HWHJYWWZi
            Y2R5aWdQNnVsaUFwL2hNM2ZRM1Y5TlEKLnU/i2DSBTyJQuARl3qZOH56YksFnCmk
            yisIsiFNMb5sTgUTDrxL0y4gvBM7jcxhcYJIM7porSQrq8AYem28Ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m53mdahgvspp3j7smcw7y7zv9jw0kjqjaktyj4g88e5jlrj3cvzs7v64ms
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T16:21:42Z"
    mac: ENC[AES256_GCM,data:pDAx3nAk4MEk7PbRF7u2JSyfvDSZssC0g0A8Ps3mxcSJ18iltqRp6JaQWRpAE/u3g6w62eO26M2A88p2AP7sastMQchEolhmRN70ly/0aPYIx4dXrgv1Q7wkJlpt5iTGzyaUrLQ16UZvEdDZg6LlTEIxocL8VrMuKmLmtKRgU0I=,iv:0EpOoNZGEgEYCGMza7/u+1n0xblIIcma8Hjr7NPcGRE=,tag:XsWXG0A71olCwfng0NDG7g==,type:str]
    version: 3.13.3
