apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
data:
  values.yaml: |
    grafana:
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        ingressClassName: tailscale
        tls:
          - hosts:
              - grafana
    prometheus:
      prometheusSpec:
        retention: 30d
        retentionSize: 15GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
